import crypto from "node:crypto";

import pg from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import {
  enqueueFinanceExpenseGeneration,
  replayFinanceExpenseGenerationJob,
  runFinanceExpenseGenerationJobs,
  type FinanceExpenseGenerationInput,
} from "./financeExpenseGeneration.js";

const URL = process.env["TEST_DATABASE_URL"],
  NOW = "2026-08-20T12:00:00.000Z",
  id = (n: number) => `12360000-0000-4000-8000-${String(n).padStart(12, "0")}`;
// prettier-ignore
const I={property:id(1),recurringCategory:id(2),otaCategory:id(3),feeCategory:id(4),rule:id(5),booking:id(6),room:id(7),commissionRule:id(8),nightRoot:id(9),nightCorrection:id(10),nightRetry:id(11),nightExhausted:id(12),nightRollback:id(13),otaRoot:id(14),otaCorrection:id(15),otaRetry:id(16),otaExhausted:id(17),otaRollback:id(18),account:id(19),payment:id(20),zeroPayment:id(21),missingPayment:id(22),rollbackPayment:id(23),fee:id(24),zeroFee:id(25),missingFee:id(26),rollbackFee:id(27),terminalEvidence:id(28),partialRule:id(29),conflictRule:id(30),permanentRule:id(31),boundedRule:id(32)} as const;
if (URL && !/(^|[_-])(test|verify)([_-]|$)/i.test(new globalThis.URL(URL).pathname))
  throw new Error("Refusing non-test database");

// prettier-ignore
describe.skipIf(!URL)("Finance expense-generation jobs (PostgreSQL)",()=>{
  const admin=new pg.Client({connectionString:URL??"postgresql://disabled"}),pool=new pg.Pool({connectionString:URL??"postgresql://disabled",max:5});
  beforeAll(async()=>{await admin.connect();await cleanup();await admin.query(`
    INSERT INTO hotel_catalog.properties(id,public_id,display_name) VALUES('${I.property}','vay-1236','Expense jobs');
    INSERT INTO pms.property_pricing_settings(property_id,currency) VALUES('${I.property}','EUR');
    INSERT INTO finance.expense_categories(id,property_id,system_key,name,color) VALUES
      ('${I.recurringCategory}','${I.property}',NULL,'Operations','#111111'),('${I.otaCategory}','${I.property}','ota_commission','OTA','#222222'),('${I.feeCategory}','${I.property}','platform_fees','Fees','#333333');
    INSERT INTO finance.recurring_expense_rules(id,property_id,category_id,cadence,starts_on,next_due_on,ends_on,vendor,amount,currency,payment_status,revision) VALUES
      ('${I.rule}','${I.property}','${I.recurringCategory}','weekly','2026-08-20','2026-08-20',NULL,'Rent',10,'EUR','unpaid',1),
      ('${I.partialRule}','${I.property}','${I.recurringCategory}','weekly','2026-08-21','2026-08-21','2026-08-21','Healthy',11,'EUR','unpaid',1),
      ('${I.conflictRule}','${I.property}','${I.recurringCategory}','weekly','2026-08-22','2026-08-22',NULL,'Conflict',12,'EUR','unpaid',2147483647),
      ('${I.permanentRule}','${I.property}','${I.recurringCategory}','weekly','9999-12-31','9999-12-31',NULL,'Exhausted',13,'EUR','unpaid',1),
      ('${I.boundedRule}','${I.property}','${I.recurringCategory}','weekly','2026-02-26','2026-02-26',NULL,'Catch-up',14,'EUR','unpaid',1);
    INSERT INTO finance.recurring_expense_rules(property_id,category_id,cadence,starts_on,next_due_on,ends_on,vendor,amount,currency,payment_status)
      SELECT '${I.property}','${I.recurringCategory}','weekly','2026-08-18','2026-08-18','2026-08-18','Page '||value,15,'EUR','unpaid' FROM generate_series(1,51) value;
    INSERT INTO finance.recurring_expense_rules(id,property_id,category_id,cadence,starts_on,next_due_on,ends_on,vendor,amount,currency,payment_status)
      SELECT ('12360000-0000-4000-9000-'||lpad(value::text,12,'0'))::uuid,'${I.property}','${I.recurringCategory}','weekly','2026-08-19','2026-08-19','2026-08-19',CASE WHEN value<=50 THEN 'Blocked '||value ELSE 'Survivor' END,16,'EUR','unpaid' FROM generate_series(1,51) value;
    INSERT INTO finance.expenses(id,property_id,category_id,origin,entry_kind,incurred_on,vendor,amount,currency,payment_status,recurring_rule_id,source_key)
      SELECT ('12360000-0000-4000-a000-'||lpad(value::text,12,'0'))::uuid,'${I.property}','${I.recurringCategory}','recurring','expense','2026-08-19','Backfill '||value,16,'EUR','unpaid',('12360000-0000-4000-9000-'||lpad(value::text,12,'0'))::uuid,'recurring_rule:12360000-0000-4000-9000-'||lpad(value::text,12,'0')||':occurrence:2026-08-19' FROM generate_series(1,50) value;
    INSERT INTO booking.guest_bookings(id,property_id,public_reference,lifecycle_status,check_in,check_out,currency) VALUES('${I.booking}','${I.property}','vay1236','completed','2026-08-20','2026-08-21','EUR');
    INSERT INTO booking.nightly_revenue_room_scopes VALUES('${I.property}','${I.room}');
    INSERT INTO finance.commission_rules(id,property_id,rule_scope,product,commission_type,percentage_rate,starts_at,source_system,ota_channel) VALUES('${I.commissionRule}','${I.property}','property','pms','percentage',10,'2026-01-01','finance','booking_com');
    INSERT INTO booking.nightly_revenue_evidence(id,property_id,guest_booking_id,room_type_id,stay_date,recognized_on,currency,gross_room_amount,occupied_room_nights,economic_event,lifecycle_state,source_kind,evidence_quality,source_revision,line_position,corrects_evidence_id,command_key) VALUES
      ('${I.nightRoot}','${I.property}','${I.booking}','${I.room}','2026-08-20','2026-08-20','EUR',100,1,'room_night','completed','ota','exact',1,1,NULL,'vay1236-root'),
      ('${I.nightCorrection}','${I.property}','${I.booking}','${I.room}','2026-08-20','2026-08-21','EUR',-20,0,'correction','corrected','ota','exact',2,1,'${I.nightRoot}','vay1236-correction'),
      ('${I.nightRetry}','${I.property}','${I.booking}','${I.room}','2026-08-20','2026-08-20','EUR',50,1,'room_night','completed','ota','exact',1,2,NULL,'vay1236-retry'),
      ('${I.nightExhausted}','${I.property}','${I.booking}','${I.room}','2026-08-20','2026-08-20','EUR',60,1,'room_night','completed','ota','exact',1,3,NULL,'vay1236-exhausted'),
      ('${I.nightRollback}','${I.property}','${I.booking}','${I.room}','2026-08-20','2026-08-20','EUR',70,1,'room_night','completed','ota','exact',1,4,NULL,'vay1236-rollback');
    INSERT INTO finance.ota_commission_evidence(id,booking_revenue_evidence_id,property_id,guest_booking_id,service_night,channel,currency,gross_room_amount,commission_rule_id,commission_rule_revision,percentage_rate,commission_amount,evidence_state,corrects_commission_evidence_id) VALUES
      ('${I.otaRoot}','${I.nightRoot}','${I.property}','${I.booking}','2026-08-20','booking_com','EUR',100,'${I.commissionRule}',1,10,10,'applied',NULL),
      ('${I.otaCorrection}','${I.nightCorrection}','${I.property}','${I.booking}','2026-08-20','booking_com','EUR',-20,'${I.commissionRule}',1,10,-2,'applied','${I.otaRoot}'),
      ('${I.otaRetry}','${I.nightRetry}','${I.property}','${I.booking}','2026-08-20','booking_com','EUR',50,'${I.commissionRule}',1,10,5,'applied',NULL),
      ('${I.otaExhausted}','${I.nightExhausted}','${I.property}','${I.booking}','2026-08-20','booking_com','EUR',60,'${I.commissionRule}',1,10,6,'applied',NULL),
      ('${I.otaRollback}','${I.nightRollback}','${I.property}','${I.booking}','2026-08-20','booking_com','EUR',70,'${I.commissionRule}',1,10,7,'applied',NULL);
    INSERT INTO finance.payment_provider_accounts(id,property_id,account_scope,provider,provider_account_id,status) VALUES('${I.account}','${I.property}','property','stripe','acct_vay1236','active');
    INSERT INTO finance.payments(id,property_id,provider_account_id,payment_kind,status,amount,fee_amount,net_amount,currency) VALUES
      ('${I.payment}','${I.property}','${I.account}','full','paid',100,3,97,'EUR'),('${I.zeroPayment}','${I.property}','${I.account}','full','paid',100,0,100,'EUR'),('${I.missingPayment}','${I.property}','${I.account}','full','paid',100,0,100,'EUR'),('${I.rollbackPayment}','${I.property}','${I.account}','full','paid',100,4,96,'EUR');
    INSERT INTO finance.provider_fee_evidence(id,property_id,payment_id,provider_account_id,provider,settlement_revision,evidence_state,evidence_on,evidence_at,fee_amount,currency,source_revision,source_fingerprint_hash,property_timezone,property_timezone_revision) VALUES
      ('${I.fee}','${I.property}','${I.payment}','${I.account}','stripe',1,'applied','2026-08-20',now(),3,'EUR','vay1236-fee',repeat('a',64),'Europe/Berlin','profile:1'),
      ('${I.zeroFee}','${I.property}','${I.zeroPayment}','${I.account}','stripe',1,'proven_zero','2026-08-20',now(),0,'EUR','vay1236-zero',repeat('b',64),'Europe/Berlin','profile:1'),
      ('${I.missingFee}','${I.property}','${I.missingPayment}','${I.account}','stripe',1,'missing','2026-08-20',now(),NULL,'EUR','vay1236-missing',repeat('c',64),'Europe/Berlin','profile:1'),
      ('${I.rollbackFee}','${I.property}','${I.rollbackPayment}','${I.account}','stripe',1,'applied','2026-08-20',now(),4,'EUR','vay1236-rollback',repeat('d',64),'Europe/Berlin','profile:1')`);});
  afterAll(async()=>{await cleanup();await pool.end();await admin.end();});

  it("keeps all job families idempotent, ordered, retryable, visible, and atomic",async()=>{
    const bounded=await enqueue({family:"recurring",dueThrough:"2026-08-17"});await run();expect((await admin.query("SELECT status,attempts_count::int attempts,max_attempts::int maximum FROM platform.jobs WHERE id=$1",[bounded.jobId])).rows[0]).toEqual({status:"pending",attempts:1,maximum:6});expect((await admin.query("SELECT count(*)::int count FROM finance.expenses WHERE recurring_rule_id=$1",[I.boundedRule])).rows[0].count).toBe(24);expect((await run()).succeeded).toBe(1);expect((await admin.query("SELECT count(*)::int count FROM finance.expenses WHERE recurring_rule_id=$1",[I.boundedRule])).rows[0].count).toBe(25);
    const paged=await enqueue({family:"recurring",dueThrough:"2026-08-18"});await run();expect((await admin.query("SELECT count(*)::int count FROM finance.expenses WHERE vendor LIKE 'Page %'")).rows[0].count).toBe(50);expect((await run()).succeeded).toBe(1);expect((await admin.query("SELECT count(*)::int count FROM finance.expenses WHERE vendor LIKE 'Page %'")).rows[0].count).toBe(51);expect((await admin.query("SELECT attempts_count::int attempts FROM platform.jobs WHERE id=$1",[paged.jobId])).rows[0].attempts).toBe(2);
    const starved=await enqueue({family:"recurring",dueThrough:"2026-08-19"});await run();expect((await admin.query("SELECT status,jsonb_array_length(job_metadata->'pendingNonActionableRuleIds') blocked FROM platform.jobs WHERE id=$1",[starved.jobId])).rows[0]).toEqual({status:"pending",blocked:50});expect((await admin.query("SELECT count(*)::int count FROM finance.expenses WHERE vendor='Survivor'")).rows[0].count).toBe(0);const cursorBlocker=new pg.Client({connectionString:URL});await cursorBlocker.connect();try{await cursorBlocker.query("BEGIN");await cursorBlocker.query("SELECT id FROM finance.recurring_expense_rules WHERE id='12360000-0000-4000-9000-000000000001' FOR UPDATE");expect((await run()).retryScheduled).toBe(1);}finally{await cursorBlocker.query("ROLLBACK").catch(()=>{});await cursorBlocker.end();}
    const starvedFinal=await run("2026-08-20T12:01:00.000Z"),starvedState=(await admin.query("SELECT status,job_metadata->>'outcomeCode' code,job_metadata->>'lastErrorCode' last,job_metadata?'pendingNonActionableRuleIds' pending,(SELECT error_type FROM platform.job_attempts WHERE job_id=platform.jobs.id ORDER BY attempt_number DESC LIMIT 1) attempt,(SELECT reason_code FROM platform.dead_letter_events WHERE job_id=platform.jobs.id LIMIT 1) dead,(SELECT count(*)::int FROM finance.expenses WHERE vendor='Survivor') survivors FROM platform.jobs WHERE id=$1",[starved.jobId])).rows[0];expect({incomplete:starvedFinal.incomplete,...starvedState}).toEqual({incomplete:1,status:"succeeded",code:"source_conflict",last:null,pending:false,attempt:null,dead:null,survivors:1});await admin.query("UPDATE finance.recurring_expense_rules SET active=false WHERE property_id=$1 AND vendor LIKE 'Blocked %'",[I.property]);
    const recurring=await enqueue({family:"recurring",dueThrough:"2026-08-20"});expect((await run()).succeeded).toBe(1);
    expect((await admin.query("SELECT count(*)::int count FROM finance.expenses WHERE recurring_rule_id=$1",[I.rule])).rows[0].count).toBe(1);
    const conflictSweep=await enqueue({family:"recurring",dueThrough:"2026-08-22"});expect((await run()).retryScheduled).toBe(1);expect((await admin.query("SELECT count(*)::int count FROM finance.expenses WHERE recurring_rule_id=$1",[I.partialRule])).rows[0].count).toBe(0);
    await admin.query("UPDATE platform.jobs SET run_after='9999-12-31' WHERE id=$1",[conflictSweep.jobId]);await admin.query("UPDATE finance.recurring_expense_rules SET active=false WHERE id=ANY($1::uuid[])",[[I.rule,I.conflictRule]]);await admin.query("UPDATE finance.recurring_expense_rules SET starts_on='9999-07-08',next_due_on='9999-07-08',ends_on='9999-12-23',active=true WHERE id=$1",[I.boundedRule]);
    const partialSweep=await enqueue({family:"recurring",dueThrough:"9999-12-31"});await run();expect((await admin.query("SELECT status,job_metadata->>'outcome' outcome,job_metadata->>'pendingIncompleteCode' pending,(SELECT error_metadata->>'outcome' FROM platform.job_attempts WHERE job_id=platform.jobs.id ORDER BY attempt_number DESC LIMIT 1) attempt FROM platform.jobs WHERE id=$1",[partialSweep.jobId])).rows[0]).toEqual({status:"pending",outcome:"continuation",pending:"cadence_exhausted",attempt:"continuation"});expect((await admin.query("SELECT next_due_on::text next,active FROM finance.recurring_expense_rules WHERE id=$1",[I.boundedRule])).rows[0]).toEqual({next:"9999-12-23",active:true});expect((await run()).incomplete).toBe(1);expect((await admin.query("SELECT count(*)::int count FROM finance.expenses WHERE recurring_rule_id=$1",[I.partialRule])).rows[0].count).toBe(1);expect((await admin.query("SELECT next_due_on::text next,active FROM finance.recurring_expense_rules WHERE id=$1",[I.boundedRule])).rows[0]).toEqual({next:"9999-12-23",active:false});expect((await admin.query("SELECT job_metadata->>'outcomeCode' job,job_metadata?'pendingIncompleteCode' pending,(SELECT error_metadata->>'outcomeCode' FROM platform.job_attempts WHERE job_id=platform.jobs.id ORDER BY attempt_number DESC LIMIT 1) attempt,(SELECT redacted_payload->>'outcomeCode' FROM platform.product_audit_events WHERE job_id=platform.jobs.id AND action='finance.expense_generation.incomplete' LIMIT 1) audit FROM platform.jobs WHERE id=$1",[partialSweep.jobId])).rows[0]).toEqual({job:"cadence_exhausted",pending:false,attempt:"cadence_exhausted",audit:"cadence_exhausted"});

    const correction=await enqueue({family:"ota_commission",commissionEvidenceId:I.otaCorrection});expect((await run()).retryScheduled).toBe(1);
    const root=await enqueue({family:"ota_commission",commissionEvidenceId:I.otaRoot}),duplicate=await enqueue({family:"ota_commission",commissionEvidenceId:I.otaRoot});expect(duplicate.jobId).toBe(root.jobId);
    const raced=await Promise.all([run(NOW),run(NOW)]);expect(raced.reduce((sum,value)=>sum+value.succeeded,0)).toBe(1);
    expect((await run("2026-08-20T12:01:00.000Z")).succeeded).toBe(1);
    expect((await admin.query("SELECT entry_kind FROM finance.expenses WHERE origin='ota_commission' ORDER BY created_at")).rows.map(row=>row.entry_kind)).toEqual(["expense","correction"]);

    const fee=await enqueue({family:"provider_fee",providerFeeEvidenceId:I.fee,paymentId:I.zeroPayment}),feeDuplicate=await enqueue({family:"provider_fee",providerFeeEvidenceId:I.fee,paymentId:I.payment});expect(feeDuplicate.jobId).toBe(fee.jobId);expect(fee.jobKey).toContain(`property:${I.property}:provider_fee_evidence:${I.fee}:project`);expect(correction.jobKey).toContain(`property:${I.property}:ota_commission_evidence:${I.otaCorrection}:project`);expect((await run()).succeeded).toBe(1);
    expect((await enqueue({family:"provider_fee",providerFeeEvidenceId:I.fee,paymentId:I.payment})).status).toBe("succeeded");
    await replayFinanceExpenseGenerationJob(admin as never,fee.jobId,()=>new Date(NOW));expect((await run()).replayed).toBe(1);
    expect((await admin.query("SELECT count(*)::int count FROM finance.expenses WHERE source_key=$1",[`provider_fee_evidence:${I.fee}`])).rows[0].count).toBe(1);
    await enqueue({family:"provider_fee",providerFeeEvidenceId:I.missingFee,paymentId:I.missingPayment});expect((await run()).incomplete).toBe(1);
    await enqueue({family:"provider_fee",providerFeeEvidenceId:I.zeroFee,paymentId:I.zeroPayment});expect((await run()).succeeded).toBe(1);

    await enqueue({family:"ota_commission",commissionEvidenceId:I.otaRetry});const blocker=new pg.Client({connectionString:URL});await blocker.connect();let exhausted:{jobId:string};
    try{await blocker.query("BEGIN");await blocker.query("SELECT id FROM finance.ota_commission_evidence WHERE id=$1 FOR UPDATE",[I.otaRetry]);
      expect((await run()).retryScheduled).toBe(1);await blocker.query("COMMIT");
      expect((await run("2026-08-20T12:01:00.000Z")).succeeded).toBe(1);
      exhausted=await enqueue({family:"ota_commission",commissionEvidenceId:I.otaExhausted});await admin.query("UPDATE platform.jobs SET attempts_count=9,max_attempts=11 WHERE id=$1",[exhausted.jobId]);await blocker.query("BEGIN");await blocker.query("SELECT id FROM finance.ota_commission_evidence WHERE id=$1 FOR UPDATE",[I.otaExhausted]);
      expect((await run(NOW,()=>1)).retryScheduled).toBe(1);expect(new Date((await admin.query("SELECT run_after FROM platform.jobs WHERE id=$1",[exhausted.jobId])).rows[0].run_after).getTime()).toBeLessThanOrEqual(new Date(NOW).getTime()+1_800_000);await blocker.query("COMMIT");await blocker.query("BEGIN");await blocker.query("SELECT id FROM finance.ota_commission_evidence WHERE id=$1 FOR UPDATE",[I.otaExhausted]);expect((await run("2026-08-20T12:31:00.000Z")).deadLettered).toBe(1);
    }finally{await blocker.query("ROLLBACK").catch(()=>{});await blocker.end();}
    const terminal=await enqueue({family:"ota_commission",commissionEvidenceId:I.terminalEvidence});expect((await run()).deadLettered).toBe(1);
    const dead=await admin.query("SELECT job_id::text,failure_summary,failure_payload FROM platform.dead_letter_events WHERE job_id=ANY($1::uuid[]) ORDER BY job_id",[[exhausted.jobId,terminal.jobId]]);expect(dead.rows).toHaveLength(2);expect(dead.rows.find(row=>row.job_id===exhausted.jobId)).toMatchObject({failure_summary:"Finance expense generation failed (write_unavailable).",failure_payload:{replayEligible:true}});expect(dead.rows.find(row=>row.job_id===terminal.jobId)).toMatchObject({failure_payload:{replayEligible:false}});

    const rollback=await enqueue({family:"provider_fee",providerFeeEvidenceId:I.rollbackFee,paymentId:I.rollbackPayment});await admin.query(`CREATE FUNCTION platform.vay1236_fail_outcome() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.action='finance.expense_generation.succeeded' THEN RAISE EXCEPTION 'secret late failure user@example.com';END IF;RETURN NEW;END$$;CREATE TRIGGER vay1236_fail_outcome BEFORE INSERT ON platform.product_audit_events FOR EACH ROW EXECUTE FUNCTION platform.vay1236_fail_outcome()`);
    try{await expect(run()).rejects.toThrow("secret late failure");}finally{await admin.query("DROP TRIGGER vay1236_fail_outcome ON platform.product_audit_events;DROP FUNCTION platform.vay1236_fail_outcome()");}
    const residue=await admin.query(`SELECT job.status,job.attempts_count::int attempts,(SELECT count(*)::int FROM platform.job_attempts WHERE job_id=job.id) attempt_rows,(SELECT count(*)::int FROM finance.expenses WHERE source_key=$2) expenses,(SELECT count(*)::int FROM platform.product_audit_events WHERE job_id=job.id OR target_resource_id=(SELECT id::text FROM finance.expenses WHERE source_key=$2 LIMIT 1)) audits FROM platform.jobs job WHERE job.id=$1`,[rollback.jobId,`provider_fee_evidence:${I.rollbackFee}`]);expect(residue.rows[0]).toEqual({status:"pending",attempts:0,attempt_rows:0,expenses:0,audits:0});
    const evidence=await admin.query("SELECT count(*)::int jobs,(SELECT count(*)::int FROM platform.product_audit_events WHERE property_id=$1 AND action LIKE 'finance.expense_generation.%') audits FROM platform.jobs WHERE property_id=$1",[I.property]);expect(evidence.rows[0].jobs).toBeGreaterThanOrEqual(10);expect(evidence.rows[0].audits).toBeGreaterThanOrEqual(10);expect(recurring.jobKey).toContain(`property:${I.property}:recurrence:due-through-2026-08-20`);expect(correction.jobId).toBeTruthy();
  },20_000);

  async function enqueue(value:{family:"recurring";dueThrough:string}|{family:"ota_commission";commissionEvidenceId:string}|{family:"provider_fee";providerFeeEvidenceId:string;paymentId:string}){return enqueueFinanceExpenseGeneration(admin as never,{...value,propertyId:I.property,requestId:`request-${crypto.randomUUID()}`,correlationId:`correlation-${crypto.randomUUID()}`,causationId:crypto.randomUUID(),requestedAt:NOW} as FinanceExpenseGenerationInput);}
  function run(now=NOW,random:()=>number=()=>0.5){return runFinanceExpenseGenerationJobs(pool,{limit:1,clock:()=>new Date(now),random});}
  async function cleanup(){await admin.query(`DROP TRIGGER IF EXISTS vay1236_fail_outcome ON platform.product_audit_events;DROP FUNCTION IF EXISTS platform.vay1236_fail_outcome();BEGIN;SET LOCAL session_replication_role=replica;DELETE FROM platform.product_audit_events WHERE property_id='${I.property}';DELETE FROM platform.dead_letter_events WHERE property_id='${I.property}';DELETE FROM platform.job_attempts WHERE job_id IN(SELECT id FROM platform.jobs WHERE property_id='${I.property}');DELETE FROM platform.jobs WHERE property_id='${I.property}';DELETE FROM platform.idempotency_keys WHERE property_id='${I.property}';DELETE FROM finance.expenses WHERE property_id='${I.property}';DELETE FROM finance.provider_fee_evidence WHERE property_id='${I.property}';DELETE FROM finance.payments WHERE property_id='${I.property}';DELETE FROM finance.payment_provider_accounts WHERE property_id='${I.property}';DELETE FROM finance.ota_commission_evidence WHERE property_id='${I.property}';DELETE FROM booking.nightly_revenue_evidence WHERE property_id='${I.property}';DELETE FROM booking.nightly_revenue_room_scopes WHERE property_id='${I.property}';DELETE FROM finance.commission_rules WHERE property_id='${I.property}';DELETE FROM finance.recurring_expense_rules WHERE property_id='${I.property}';DELETE FROM finance.expense_categories WHERE property_id='${I.property}';DELETE FROM booking.guest_bookings WHERE property_id='${I.property}';DELETE FROM pms.property_pricing_settings WHERE property_id='${I.property}';DELETE FROM hotel_catalog.properties WHERE id='${I.property}';COMMIT`);}
});
