export type MarketplaceColumn = readonly [jsonKey: string, sqlName: string, type: string];
export type MarketplaceTableDefinition = {
  table: string;
  key: readonly string[];
  freshness: string;
  columns: readonly MarketplaceColumn[];
};

const c = (jsonKey: string, sqlName: string, type: string): MarketplaceColumn => [
  jsonKey,
  sqlName,
  type,
];
const id = c("id", "id", "uuid");
const property = c("propertyId", "property_id", "uuid");
const created = c("createdAt", "created_at", "timestamptz");
const updated = c("updatedAt", "updated_at", "timestamptz");

export const PRODUCTION_MARKETPLACE_WRITE_ORDER = [
  "creator_profiles",
  "creator_platforms",
  "marketplace_hotel_profiles",
  "marketplace_offers",
  "offer_compensation_options",
  "offer_creator_requirements",
  "collaborations",
  "creator_ratings",
  "collaboration_deliverables",
  "marketplace_chat_messages",
  "trips",
  "external_collaborations",
  "marketplace_notifications",
  "invite_codes",
  "newsletter_preferences",
  "marketplace_offer_read_model",
] as const;

const table = (
  name: string,
  columns: readonly MarketplaceColumn[],
  freshness = "updated_at",
  key: readonly string[] = ["id"],
): MarketplaceTableDefinition => ({ table: name, columns, freshness, key });

export const PRODUCTION_MARKETPLACE_TABLES: Record<string, MarketplaceTableDefinition> = {
  creator_profiles: table("marketplace.creator_profiles", [
    id,
    c("organizationId", "organization_id", "uuid"),
    c("ownerUserId", "owner_user_id", "uuid"),
    c("sourceSystem", "source_system", "text"),
    c("sourceCreatorId", "source_creator_id", "text"),
    c("displayName", "display_name", "text"),
    c("creatorType", "creator_type", "text"),
    c("locationText", "location_text", "text"),
    c("shortDescription", "short_description", "text"),
    c("portfolioUrl", "portfolio_url", "text"),
    c("phone", "phone", "text"),
    c("profilePictureUrl", "profile_picture_url", "text"),
    c("profileComplete", "profile_complete", "boolean"),
    c("profileCompletedAt", "profile_completed_at", "timestamptz"),
    c("profileStatus", "profile_status", "text"),
    c("profileMetadata", "profile_metadata", "jsonb"),
    c("piiRetentionUntil", "pii_retention_until", "date"),
    created,
    updated,
  ]),
  creator_platforms: table("marketplace.creator_platforms", [
    id,
    c("creatorProfileId", "creator_profile_id", "uuid"),
    c("organizationId", "organization_id", "uuid"),
    c("sourceSystem", "source_system", "text"),
    c("sourcePlatformId", "source_platform_id", "text"),
    c("platform", "platform", "text"),
    c("handle", "handle", "text"),
    c("profileUrl", "profile_url", "text"),
    c("followerCount", "follower_count", "integer"),
    c("engagementRate", "engagement_rate", "numeric"),
    c("audienceCountries", "audience_countries", "jsonb"),
    c("audienceAgeGroups", "audience_age_groups", "jsonb"),
    c("audienceGenderSplit", "audience_gender_split", "jsonb"),
    c("verificationStatus", "verification_status", "text"),
    c("platformMetadata", "platform_metadata", "jsonb"),
    created,
    updated,
  ]),
  marketplace_hotel_profiles: table(
    "marketplace.marketplace_hotel_profiles",
    [
      property,
      c("organizationId", "organization_id", "uuid"),
      c("sourceSystem", "source_system", "text"),
      c("sourceHotelProfileId", "source_hotel_profile_id", "text"),
      c("marketplaceProfileStatus", "marketplace_profile_status", "text"),
      c("profileComplete", "profile_complete", "boolean"),
      c("profileCompletedAt", "profile_completed_at", "timestamptz"),
      c("hostSummary", "host_summary", "text"),
      c("collaborationGuidelines", "collaboration_guidelines", "text"),
      c("marketplaceMetadata", "marketplace_metadata", "jsonb"),
      created,
      updated,
    ],
    "updated_at",
    ["property_id"],
  ),
  marketplace_offers: table("marketplace.marketplace_offers", [
    id,
    property,
    c("organizationId", "organization_id", "uuid"),
    c("sourceSystem", "source_system", "text"),
    c("sourceOfferId", "source_offer_id", "text"),
    c("title", "title", "text"),
    c("offerSummary", "offer_summary", "text"),
    c("accommodationType", "accommodation_type", "text"),
    c("offerStatus", "offer_status", "text"),
    c("rawLocationText", "raw_location_text", "text"),
    c("imageUrls", "image_urls", "text[]"),
    c("offerMetadata", "offer_metadata", "jsonb"),
    created,
    updated,
  ]),
  offer_compensation_options: table("marketplace.offer_compensation_options", [
    id,
    c("offerId", "offer_id", "uuid"),
    property,
    c("organizationId", "organization_id", "uuid"),
    c("sourceSystem", "source_system", "text"),
    c("sourceCompensationOptionId", "source_compensation_option_id", "text"),
    c("compensationType", "compensation_type", "text"),
    c("availabilityMonths", "availability_months", "text[]"),
    c("platforms", "platforms", "text[]"),
    c("freeStayMinNights", "free_stay_min_nights", "integer"),
    c("freeStayMaxNights", "free_stay_max_nights", "integer"),
    c("paidMaxAmount", "paid_max_amount", "numeric"),
    c("discountPercentage", "discount_percentage", "integer"),
    c("commissionPercentage", "commission_percentage", "numeric"),
    c("minFollowers", "min_followers", "integer"),
    c("currency", "currency", "text"),
    c("termsSummary", "terms_summary", "text"),
    c("compensationMetadata", "compensation_metadata", "jsonb"),
    created,
    updated,
  ]),
  offer_creator_requirements: table("marketplace.offer_creator_requirements", [
    id,
    c("offerId", "offer_id", "uuid"),
    property,
    c("organizationId", "organization_id", "uuid"),
    c("sourceSystem", "source_system", "text"),
    c("sourceRequirementId", "source_requirement_id", "text"),
    c("platforms", "platforms", "text[]"),
    c("targetCountries", "target_countries", "text[]"),
    c("targetAgeMin", "target_age_min", "integer"),
    c("targetAgeMax", "target_age_max", "integer"),
    c("targetAgeGroups", "target_age_groups", "text[]"),
    c("creatorTypes", "creator_types", "text[]"),
    c("requirementMetadata", "requirement_metadata", "jsonb"),
    created,
    updated,
  ]),
  collaborations: table("marketplace.collaborations", [
    id,
    c("creatorProfileId", "creator_profile_id", "uuid"),
    c("creatorOrganizationId", "creator_organization_id", "uuid"),
    property,
    c("hotelOrganizationId", "hotel_organization_id", "uuid"),
    c("offerId", "offer_id", "uuid"),
    c("commissionRuleId", "commission_rule_id", "uuid"),
    c("sourceSystem", "source_system", "text"),
    c("sourceCollaborationId", "source_collaboration_id", "text"),
    c("initiatorType", "initiator_type", "text"),
    c("lifecycleStatus", "lifecycle_status", "text"),
    c("compensationType", "compensation_type", "text"),
    c("applicationMessage", "application_message", "text"),
    c("negotiatedTerms", "negotiated_terms", "jsonb"),
    c("platformDeliverables", "platform_deliverables", "jsonb"),
    c("preferredMonths", "preferred_months", "text[]"),
    c("travelDateFrom", "travel_date_from", "date"),
    c("travelDateTo", "travel_date_to", "date"),
    c("preferredDateFrom", "preferred_date_from", "date"),
    c("preferredDateTo", "preferred_date_to", "date"),
    c("freeStayMinNights", "free_stay_min_nights", "integer"),
    c("freeStayMaxNights", "free_stay_max_nights", "integer"),
    c("paidAmount", "paid_amount", "numeric"),
    c("discountPercentage", "discount_percentage", "integer"),
    c("affiliateCommissionPercentage", "affiliate_commission_percentage", "numeric"),
    c("affiliateEnabled", "affiliate_enabled", "boolean"),
    c("currency", "currency", "text"),
    c("affiliateReferralCode", "affiliate_referral_code", "text"),
    c("affiliateLink", "affiliate_link", "text"),
    c("creatorConsent", "creator_consent", "boolean"),
    c("hotelAgreedAt", "hotel_agreed_at", "timestamptz"),
    c("creatorAgreedAt", "creator_agreed_at", "timestamptz"),
    c("termLastUpdatedAt", "term_last_updated_at", "timestamptz"),
    c("respondedAt", "responded_at", "timestamptz"),
    c("cancelledAt", "cancelled_at", "timestamptz"),
    c("completedAt", "completed_at", "timestamptz"),
    c("collaborationMetadata", "collaboration_metadata", "jsonb"),
    created,
    updated,
  ]),
  creator_ratings: table("marketplace.creator_ratings", [
    id,
    c("creatorProfileId", "creator_profile_id", "uuid"),
    c("creatorOrganizationId", "creator_organization_id", "uuid"),
    property,
    c("hotelOrganizationId", "hotel_organization_id", "uuid"),
    c("collaborationId", "collaboration_id", "uuid"),
    c("rating", "rating", "integer"),
    c("comment", "comment", "text"),
    c("createdByUserId", "created_by_user_id", "uuid"),
    created,
    updated,
  ]),
  collaboration_deliverables: table("marketplace.collaboration_deliverables", [
    id,
    c("collaborationId", "collaboration_id", "uuid"),
    property,
    c("platform", "platform", "text"),
    c("deliverableType", "deliverable_type", "text"),
    c("quantity", "quantity", "integer"),
    c("deliverableStatus", "deliverable_status", "text"),
    c("dueAt", "due_at", "timestamptz"),
    c("submittedAt", "submitted_at", "timestamptz"),
    c("completedAt", "completed_at", "timestamptz"),
    c("contentUrl", "content_url", "text"),
    c("reviewNotes", "review_notes", "text"),
    c("deliverableMetadata", "deliverable_metadata", "jsonb"),
    created,
    updated,
  ]),
  marketplace_chat_messages: table(
    "marketplace.marketplace_chat_messages",
    [
      id,
      c("collaborationId", "collaboration_id", "uuid"),
      property,
      c("senderUserId", "sender_user_id", "uuid"),
      c("senderType", "sender_type", "text"),
      c("messageType", "message_type", "text"),
      c("body", "body", "text"),
      c("messageMetadata", "message_metadata", "jsonb"),
      c("readAt", "read_at", "timestamptz"),
      c("piiRetentionUntil", "pii_retention_until", "date"),
      created,
    ],
    "COALESCE(read_at, created_at)",
  ),
  trips: table("marketplace.trips", [
    id,
    c("creatorProfileId", "creator_profile_id", "uuid"),
    c("organizationId", "organization_id", "uuid"),
    c("sourceSystem", "source_system", "text"),
    c("sourceTripId", "source_trip_id", "text"),
    c("name", "name", "text"),
    c("locationText", "location_text", "text"),
    c("startDate", "start_date", "date"),
    c("endDate", "end_date", "date"),
    c("notes", "notes", "text"),
    c("tripMetadata", "trip_metadata", "jsonb"),
    created,
    updated,
  ]),
  external_collaborations: table("marketplace.external_collaborations", [
    id,
    c("creatorProfileId", "creator_profile_id", "uuid"),
    c("organizationId", "organization_id", "uuid"),
    c("tripId", "trip_id", "uuid"),
    c("sourceSystem", "source_system", "text"),
    c("sourceExternalCollaborationId", "source_external_collaboration_id", "text"),
    c("title", "title", "text"),
    c("hotelName", "hotel_name", "text"),
    c("locationText", "location_text", "text"),
    c("collaborationType", "collaboration_type", "text"),
    c("startDate", "start_date", "date"),
    c("endDate", "end_date", "date"),
    c("deliverablesSummary", "deliverables_summary", "text"),
    c("notes", "notes", "text"),
    c("externalMetadata", "external_metadata", "jsonb"),
    created,
    updated,
  ]),
  marketplace_notifications: table(
    "marketplace.marketplace_notifications",
    [
      id,
      c("recipientUserId", "recipient_user_id", "uuid"),
      c("organizationId", "organization_id", "uuid"),
      c("notificationType", "notification_type", "text"),
      c("title", "title", "text"),
      c("body", "body", "text"),
      c("linkUrl", "link_url", "text"),
      c("resourceType", "resource_type", "text"),
      c("resourceId", "resource_id", "text"),
      c("notificationMetadata", "notification_metadata", "jsonb"),
      c("readAt", "read_at", "timestamptz"),
      created,
    ],
    "COALESCE(read_at, created_at)",
  ),
  invite_codes: table(
    "marketplace.invite_codes",
    [
      id,
      c("code", "code", "text"),
      c("inviteType", "invite_type", "text"),
      c("status", "status", "text"),
      c("payload", "payload", "jsonb"),
      c("createdByUserId", "created_by_user_id", "uuid"),
      c("redeemedByUserId", "redeemed_by_user_id", "uuid"),
      c("creatorProfileId", "creator_profile_id", "uuid"),
      c("creatorOrganizationId", "creator_organization_id", "uuid"),
      property,
      c("redeemedAt", "redeemed_at", "timestamptz"),
      c("expiresAt", "expires_at", "timestamptz"),
      created,
    ],
    "COALESCE(redeemed_at, created_at)",
  ),
  newsletter_preferences: table("marketplace.newsletter_preferences", [
    id,
    c("userId", "user_id", "uuid"),
    c("organizationId", "organization_id", "uuid"),
    c("enabled", "enabled", "boolean"),
    c("countryFilter", "country_filter", "text[]"),
    c("sourceSystem", "source_system", "text"),
    c("sourcePreferenceId", "source_preference_id", "text"),
    created,
    updated,
  ]),
  marketplace_offer_read_model: table(
    "marketplace.marketplace_offer_read_model",
    [
      c("offerId", "offer_id", "uuid"),
      property,
      c("publicId", "public_id", "text"),
      c("canonicalSlug", "canonical_slug", "text"),
      c("displayName", "display_name", "text"),
      c("offerTitle", "offer_title", "text"),
      c("offerSummary", "offer_summary", "text"),
      c("accommodationType", "accommodation_type", "text"),
      c("visibilityStatus", "visibility_status", "text"),
      c("location", "location", "jsonb"),
      c("imageUrls", "image_urls", "text[]"),
      c("publicCompensationSummary", "public_compensation_summary", "jsonb"),
      c("publicCreatorRequirements", "public_creator_requirements", "jsonb"),
      c("sourceFreshness", "source_freshness", "jsonb"),
      c("projectedAt", "projected_at", "timestamptz"),
    ],
    "projected_at",
    ["offer_id"],
  ),
};
